sonar.projectKey=QuelloCheVuoiTu_Muses
sonar.organization=quellochevuoitusonar
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.min.js,**/dist/**,**/build/**,**/coverage/**,**/.git/**,**/*.spec.js,**/*.test.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*Test.java,**/*Spec.java
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.java.coveragePlugin=jacoco
sonar.java.binaries=target/classes
sonar.java.libraries=target/*.jar
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit.xml
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/*Test.java,**/*Spec.java
sonar.verbose=false
